title: [Sync for Reddit]
description: [A beautiful Reddit app for browsing Reddit on the go!]

remote_theme: just-the-docs/just-the-docs
search_enabled: true
color_scheme: dark
$link-color: $blue-000;
nav_sort: case_insensitive