title: [Sync for Reddit]
description: [A beautiful Reddit app for browsing Reddit on the go!]

remote_theme: just-the-docs/just-the-docs
search_enabled: true
$link-color: $blue-000;
nav_sort: case_insensitive
heading_anchors: true

aux_links:
  "Download Sync from Google Play":
    - "https://play.google.com/store/apps/details?id=com.laurencedawson.reddit_sync"